import fs from "fs";
import path from "path";

import Head from "next/head";

import AndromedaNavbar from "../components/Navbar";
import ProductGrid from "../components/ProductGrid";

// This gets called on every request
export async function getServerSideProps() {
    const cardsJson = JSON.parse(
        fs.readFileSync(
            path.join(process.cwd(), `server`, `cards.json`),
            `utf8`
        )
    );

    // Pass data to the page via props
    return { props: { cards: Object.values(cardsJson).slice(0, 10) } };
}

export default function Home({ cards }) {
    return (
        <>
            <Head>
                <title>Andromeda Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/andromeda.ico" />
            </Head>
            <AndromedaNavbar />
            <ProductGrid cards={cards} />
        </>
    );
}
