import Head from "next/head";

import AndromedaNavbar from "../components/Navbar";
import ProductGrid from "../components/ProductGrid";

export default function Home() {
    return (
        <>
            <Head>
                <title>Andromeda Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/andromeda.ico" />
            </Head>
            <AndromedaNavbar />
            <ProductGrid />
        </>
    );
}
